<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>Falloutization.Equipment</RootNamespace>
    <AssemblyName>FalloutizationEquipment</AssemblyName>
    <LangVersion>12</LangVersion>
    <Deterministic>true</Deterministic>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Copyright>Copyright ©Canenald 2026</Copyright>
    <Authors>Canenald</Authors>
    <Product>Falloutization.Equipment</Product>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\Assemblies\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <Optimize>true</Optimize>
    <OutputPath>..\Assemblies\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.*-*" />
    <PackageReference Include="Lib.Harmony" Version="2.3.3">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Verse" />
    <Using Include="RimWorld" />
    <Using Include="System.Collections.Generic" />
    <Using Include="System.Linq" />
  </ItemGroup>
</Project>
